### PR TITLE
Fix snap build

### PR DESCRIPTION
**Pull request by toabctl**
Commit ec1eab1717c65e renamed the executable so reflect this rename in the snap build, too.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by agraf — APPROVED** [review]

**Comment by agraf** [comment]
@toabctl Thanks for the patch! Would you mind to sign it so I can merge?

**Comment by toabctl** [comment]
@agraf signed.

**Comment by agraf** [comment]
@toabctl Github still complains:

>The email in this signature doesn’t match the committer email.

**Comment by toabctl** [comment]
@agraf solved. sorry

**Pull request merged**
