### PR TITLE
Restructure code to make it pip installable

### PR DESCRIPTION
**Pull request by toabctl**
This PR changes the code structure to make it pip-installable . That way, it's easier to use and easier to package for others.
The change still keeps compatibility so AWS documentation is still valid.

### CODE REVIEW

**Comment by toabctl** [comment]
cc @agraf

**Comment by toabctl** [comment]
I tested this now with:

1. just downloading the repo and using directly `./uefivars.py` (as documented by AWS):
```
$ ./uefivars.py -i none -o aws -O your_binary_blob.bin -P ~/tmp/kp/PK.esl -K ~/tmp/kp/KEK.esl --db ~/tmp/kp/db.esl --dbx /usr/share/secureboot/updates/dbx/dbxupdate_x64.bin 
Read 0 variables
Writen 4 variables
```

2. installing it in a venv and execute it from there:
```
$ virtualenv venv && source venv/bin/activate && pip install -e .
$ which uefivars.py 
~/devel/python-uefivars/venv/bin/uefivars.py
$ uefivars.py -i none -o aws -O your_binary_blob.bin -P ~/tmp/kp/PK.esl -K ~/tmp/kp/KEK.esl --db ~/tmp/kp/db.esl --dbx /usr/share/secureboot/updates/dbx/dbxupdate_x64.bin 
Read 0 variables
Writen 4 variables
```

So both variants seem to work now.

**Comment by toabctl** [comment]
@agraf I think this is now ready for review.

**Comment by toabctl** [comment]
@agraf friendly ping...

**Comment by toabctl** [comment]
@agraf @kernelmoja friendly ping ...

**Comment by kernelmoja** [comment]
Thank you so much for the contribution and sorry for the delay in responses!

**Pull request merged**
